services:
  backend:
    image: 21amir21/golang-server-tf:1.0.0
    container_name: golang-server
    volumes:
      - .:/app
      # TODO: might be needed and might not be needed
      # - ./terraform:/app/terraform:ro   # mount only terraform files so terraform CLI works
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
   image: mongo
   container_name: mongo
   command: ["--replSet", "rs0", "--bind_ip_all"]
   restart: always
   volumes:
     - mongo-data:/data/db
   ports:
     - "2717:27017"
  #  environment:
  #    - MONGO_URI=${MONGO_URI}
  #    - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
     
    

volumes:
  mongo-data: